from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from pathlib import Path
from datetime import datetime
from os import environ


def check_migrations(config):
    try:
        command.check(config)
    except AutogenerateDiffsDetected as e:
        for diff in e.diffs:
            print(" -", diff)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        message_time = f"update_{timestamp}"
        command.revision(config, message=message_time, autogenerate=True, )


def upgrade_head(config):
    command.upgrade(config, "head")


def main():
    db_user = environ['DB_USER']
    db_pass = environ['DB_PASS']
    db_name = environ['DB_NAME']

    db_url = f"postgresql://{db_user}:{db_pass}@localhost:5432/{db_name}"
    config = Config(Path(__file__).parent / "alembic.ini")
    config.set_main_option("sqlalchemy.url", db_url.replace('%', '%%'))

    while True:
        option = input("\nDesea hacer check y revisión o upgrade (c/u): ").lower()
        if option == "c":
            check_migrations(config)
            break
        elif option == "u":
            upgrade_head(config)
            break
        else:
            print("Opción inválida, intente de nuevo.")

if __name__ == "__main__":
    main()
