"""update_20251205_011805

Revision ID: d0efa709c1ec
Revises: c3b75c7bc95b
Create Date: 2025-12-05 01:18:05.753278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0efa709c1ec'
down_revision: Union[str, Sequence[str], None] = 'c3b75c7bc95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('min_repeats', sa.Integer(), nullable=True),
    sa.Column('max_repeats', sa.Integer(), nullable=True),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_exercise')
    # ### end Alembic commands ###
