"""update_20251205_005827

Revision ID: a1f32e878c0d
Revises: c3b75c7bc95b
Create Date: 2025-12-05 00:58:27.599412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f32e878c0d'
down_revision: Union[str, Sequence[str], None] = 'c3b75c7bc95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('rutine_id', sa.Integer(), nullable=True),
    sa.Column('min_repeats', sa.Integer(), nullable=True),
    sa.Column('max_repeats', sa.Integer(), nullable=True),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['routine_exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['rutine_id'], ['routine_exercise.rutine_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_exercise')
    # ### end Alembic commands ###
