"""update_20251206_014218

Revision ID: f26a38a52355
Revises: d0efa709c1ec
Create Date: 2025-12-06 01:42:18.897069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26a38a52355'
down_revision: Union[str, Sequence[str], None] = 'd0efa709c1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('foods', sa.Column('food_url', sa.String(), nullable=False))
    op.drop_column('foods', 'grams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('foods', 'food_url')
    op.drop_column('foods', 'calories')
    # ### end Alembic commands ###
