"""update_20251210_205809

Revision ID: 1ca8038d2a44
Revises: 5ba7c06baab3
Create Date: 2025-12-10 20:58:09.787004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8038d2a44'
down_revision: Union[str, Sequence[str], None] = '5ba7c06baab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('foods_meal_id_fkey'), 'foods', type_='foreignkey')
    op.drop_column('foods', 'meal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('foods_meal_id_fkey'), 'foods', 'meals', ['meal_id'], ['id'])
    # ### end Alembic commands ###
